import { createElement } from 'react';
import createLucideIconModule from 'lucide-react/dist/esm/createLucideIcon.js';
import { __iconNode as activityNode } from 'lucide-react/dist/esm/icons/activity.js';
import { __iconNode as triangleAlertNode } from 'lucide-react/dist/esm/icons/triangle-alert.js';
import { __iconNode as arrowLeftNode } from 'lucide-react/dist/esm/icons/arrow-left.js';
import { __iconNode as arrowRightNode } from 'lucide-react/dist/esm/icons/arrow-right.js';
import { __iconNode as chartColumnNode } from 'lucide-react/dist/esm/icons/chart-column.js';
import { __iconNode as bellNode } from 'lucide-react/dist/esm/icons/bell.js';
import { __iconNode as bellRingNode } from 'lucide-react/dist/esm/icons/bell-ring.js';
import { __iconNode as building2Node } from 'lucide-react/dist/esm/icons/building-2.js';
import { __iconNode as calendarNode } from 'lucide-react/dist/esm/icons/calendar.js';
import { __iconNode as calendarClockNode } from 'lucide-react/dist/esm/icons/calendar-clock.js';
import { __iconNode as cameraNode } from 'lucide-react/dist/esm/icons/camera.js';
import { __iconNode as checkNode } from 'lucide-react/dist/esm/icons/check.js';
import { __iconNode as checkCheckNode } from 'lucide-react/dist/esm/icons/check-check.js';
import { __iconNode as circleCheckNode } from 'lucide-react/dist/esm/icons/circle-check.js';
import { __iconNode as chevronDownNode } from 'lucide-react/dist/esm/icons/chevron-down.js';
import { __iconNode as chevronLeftNode } from 'lucide-react/dist/esm/icons/chevron-left.js';
import { __iconNode as chevronRightNode } from 'lucide-react/dist/esm/icons/chevron-right.js';
import { __iconNode as circleHelpNode } from 'lucide-react/dist/esm/icons/circle-help.js';
import { __iconNode as clockNode } from 'lucide-react/dist/esm/icons/clock.js';
import { __iconNode as clock3Node } from 'lucide-react/dist/esm/icons/clock-3.js';
import { __iconNode as creditCardNode } from 'lucide-react/dist/esm/icons/credit-card.js';
import { __iconNode as downloadNode } from 'lucide-react/dist/esm/icons/download.js';
import { __iconNode as eyeNode } from 'lucide-react/dist/esm/icons/eye.js';
import { __iconNode as eyeOffNode } from 'lucide-react/dist/esm/icons/eye-off.js';
import { __iconNode as filePenNode } from 'lucide-react/dist/esm/icons/file-pen.js';
import { __iconNode as fileTextNode } from 'lucide-react/dist/esm/icons/file-text.js';
import { __iconNode as folderOpenNode } from 'lucide-react/dist/esm/icons/folder-open.js';
import { __iconNode as folderPlusNode } from 'lucide-react/dist/esm/icons/folder-plus.js';
import { __iconNode as earthNode } from 'lucide-react/dist/esm/icons/earth.js';
import { __iconNode as historyNode } from 'lucide-react/dist/esm/icons/history.js';
import { __iconNode as infoNode } from 'lucide-react/dist/esm/icons/info.js';
import { __iconNode as layoutDashboardNode } from 'lucide-react/dist/esm/icons/layout-dashboard.js';
import { __iconNode as link2Node } from 'lucide-react/dist/esm/icons/link-2.js';
import { __iconNode as loaderCircleNode } from 'lucide-react/dist/esm/icons/loader-circle.js';
import { __iconNode as lockNode } from 'lucide-react/dist/esm/icons/lock.js';
import { __iconNode as logOutNode } from 'lucide-react/dist/esm/icons/log-out.js';
import { __iconNode as mailNode } from 'lucide-react/dist/esm/icons/mail.js';
import { __iconNode as megaphoneNode } from 'lucide-react/dist/esm/icons/megaphone.js';
import { __iconNode as menuNode } from 'lucide-react/dist/esm/icons/menu.js';
import { __iconNode as messageCircleNode } from 'lucide-react/dist/esm/icons/message-circle.js';
import { __iconNode as messageSquareNode } from 'lucide-react/dist/esm/icons/message-square.js';
import { __iconNode as moonNode } from 'lucide-react/dist/esm/icons/moon.js';
import { __iconNode as ellipsisNode } from 'lucide-react/dist/esm/icons/ellipsis.js';
import { __iconNode as pauseNode } from 'lucide-react/dist/esm/icons/pause.js';
import { __iconNode as pencilNode } from 'lucide-react/dist/esm/icons/pencil.js';
import { __iconNode as phoneNode } from 'lucide-react/dist/esm/icons/phone.js';
import { __iconNode as playNode } from 'lucide-react/dist/esm/icons/play.js';
import { __iconNode as plugNode } from 'lucide-react/dist/esm/icons/plug.js';
import { __iconNode as plusNode } from 'lucide-react/dist/esm/icons/plus.js';
import { __iconNode as circlePlusNode } from 'lucide-react/dist/esm/icons/circle-plus.js';
import { __iconNode as receiptNode } from 'lucide-react/dist/esm/icons/receipt.js';
import { __iconNode as refreshCwNode } from 'lucide-react/dist/esm/icons/refresh-cw.js';
import { __iconNode as rocketNode } from 'lucide-react/dist/esm/icons/rocket.js';
import { __iconNode as rotateCcwNode } from 'lucide-react/dist/esm/icons/rotate-ccw.js';
import { __iconNode as scrollTextNode } from 'lucide-react/dist/esm/icons/scroll-text.js';
import { __iconNode as searchNode } from 'lucide-react/dist/esm/icons/search.js';
import { __iconNode as sendNode } from 'lucide-react/dist/esm/icons/send.js';
import { __iconNode as settingsNode } from 'lucide-react/dist/esm/icons/settings.js';
import { __iconNode as settings2Node } from 'lucide-react/dist/esm/icons/settings-2.js';
import { __iconNode as share2Node } from 'lucide-react/dist/esm/icons/share-2.js';
import { __iconNode as shieldNode } from 'lucide-react/dist/esm/icons/shield.js';
import { __iconNode as shieldCheckNode } from 'lucide-react/dist/esm/icons/shield-check.js';
import { __iconNode as storeNode } from 'lucide-react/dist/esm/icons/store.js';
import { __iconNode as sunNode } from 'lucide-react/dist/esm/icons/sun.js';
import { __iconNode as trash2Node } from 'lucide-react/dist/esm/icons/trash-2.js';
import { __iconNode as trendingUpNode } from 'lucide-react/dist/esm/icons/trending-up.js';
import { __iconNode as unplugNode } from 'lucide-react/dist/esm/icons/unplug.js';
import { __iconNode as uploadNode } from 'lucide-react/dist/esm/icons/upload.js';
import { __iconNode as userNode } from 'lucide-react/dist/esm/icons/user.js';
import { __iconNode as userPlusNode } from 'lucide-react/dist/esm/icons/user-plus.js';
import { __iconNode as userRoundNode } from 'lucide-react/dist/esm/icons/user-round.js';
import { __iconNode as usersNode } from 'lucide-react/dist/esm/icons/users.js';
import { __iconNode as walletNode } from 'lucide-react/dist/esm/icons/wallet.js';
import { __iconNode as webhookNode } from 'lucide-react/dist/esm/icons/webhook.js';
import { __iconNode as xNode } from 'lucide-react/dist/esm/icons/x.js';
import { __iconNode as xCircleNode } from 'lucide-react/dist/esm/icons/circle-x.js';
import { __iconNode as zapNode } from 'lucide-react/dist/esm/icons/zap.js';
import { isIcon } from './isIcon';

const createLucideIcon =
  typeof createLucideIconModule === 'function'
    ? createLucideIconModule
    : createLucideIconModule?.default;

function EmptyIcon() {
  return null;
}

function icon(name, node) {
  if (typeof createLucideIcon !== 'function' || !Array.isArray(node)) return EmptyIcon;
  const Inner = createLucideIcon(name, node);
  function LucideIcon(props) {
    if (!isIcon(Inner)) return null;
    return createElement(Inner, props);
  }
  LucideIcon.displayName = name;
  return LucideIcon;
}

export const Activity = icon('activity', activityNode);
export const AlertTriangle = icon('triangle-alert', triangleAlertNode);
export const ArrowLeft = icon('arrow-left', arrowLeftNode);
export const ArrowRight = icon('arrow-right', arrowRightNode);
export const BarChart3 = icon('chart-column', chartColumnNode);
export const Bell = icon('bell', bellNode);
export const BellRing = icon('bell-ring', bellRingNode);
export const Building2 = icon('building-2', building2Node);
export const Calendar = icon('calendar', calendarNode);
export const CalendarClock = icon('calendar-clock', calendarClockNode);
export const Camera = icon('camera', cameraNode);
export const Check = icon('check', checkNode);
export const CheckCheck = icon('check-check', checkCheckNode);
export const CheckCircle2 = icon('circle-check', circleCheckNode);
export const ChevronDown = icon('chevron-down', chevronDownNode);
export const ChevronLeft = icon('chevron-left', chevronLeftNode);
export const ChevronRight = icon('chevron-right', chevronRightNode);
export const CircleHelp = icon('circle-help', circleHelpNode);
export const Clock = icon('clock', clockNode);
export const Clock3 = icon('clock-3', clock3Node);
export const CreditCard = icon('credit-card', creditCardNode);
export const Download = icon('download', downloadNode);
export const Eye = icon('eye', eyeNode);
export const EyeOff = icon('eye-off', eyeOffNode);
export const FileEdit = icon('file-pen', filePenNode);
export const FileText = icon('file-text', fileTextNode);
export const FolderOpen = icon('folder-open', folderOpenNode);
export const FolderPlus = icon('folder-plus', folderPlusNode);
export const Globe2 = icon('earth', earthNode);
export const History = icon('history', historyNode);
export const Info = icon('info', infoNode);
export const LayoutDashboard = icon('layout-dashboard', layoutDashboardNode);
export const Link2 = icon('link-2', link2Node);
export const Loader2 = icon('loader-circle', loaderCircleNode);
export const Lock = icon('lock', lockNode);
export const LogOut = icon('log-out', logOutNode);
export const Mail = icon('mail', mailNode);
export const Megaphone = icon('megaphone', megaphoneNode);
export const Menu = icon('menu', menuNode);
export const MessageCircle = icon('message-circle', messageCircleNode);
export const MessageSquare = icon('message-square', messageSquareNode);
export const Moon = icon('moon', moonNode);
export const MoreHorizontal = icon('ellipsis', ellipsisNode);
export const Pause = icon('pause', pauseNode);
export const Pencil = icon('pencil', pencilNode);
export const Phone = icon('phone', phoneNode);
export const Play = icon('play', playNode);
export const Plug = icon('plug', plugNode);
export const Plus = icon('plus', plusNode);
export const PlusCircle = icon('circle-plus', circlePlusNode);
export const Receipt = icon('receipt', receiptNode);
export const RefreshCw = icon('refresh-cw', refreshCwNode);
export const Rocket = icon('rocket', rocketNode);
export const RotateCcw = icon('rotate-ccw', rotateCcwNode);
export const ScrollText = icon('scroll-text', scrollTextNode);
export const Search = icon('search', searchNode);
export const Send = icon('send', sendNode);
export const Settings = icon('settings', settingsNode);
export const Settings2 = icon('settings-2', settings2Node);
export const Share2 = icon('share-2', share2Node);
export const Shield = icon('shield', shieldNode);
export const ShieldCheck = icon('shield-check', shieldCheckNode);
export const Store = icon('store', storeNode);
export const Sun = icon('sun', sunNode);
export const Trash2 = icon('trash-2', trash2Node);
export const TrendingUp = icon('trending-up', trendingUpNode);
export const Unplug = icon('unplug', unplugNode);
export const Upload = icon('upload', uploadNode);
export const User = icon('user', userNode);
export const UserPlus = icon('user-plus', userPlusNode);
export const UserRound = icon('user-round', userRoundNode);
export const Users = icon('users', usersNode);
export const Wallet = icon('wallet', walletNode);
export const Webhook = icon('webhook', webhookNode);
export const X = icon('x', xNode);
export const XCircle = icon('x-circle', xCircleNode);
export const Zap = icon('zap', zapNode);
